### ISSUE TITLE
Mod's Skill Icons and Shotgun Recharge bugs

### ISSUE THREAD

**Issue by BitzThe8Bit** [taytaytorro/EngiGamingRedux#3]
The skill icons for the Gauss Scatter and Plasma Grenade are completely white, obviously not much of a big deal, a lot of mods have skill icons like that, however, there's a much more substantial bug which involves running out of ammo on the Gauss Scatter, forcing you to wait for it to recharge all the way back up and not allowing you to use any of your other skills for the mean time, including placing turrets.

EDIT: Also happens if you let the shotgun charge at _any_ point and will additionally briefly cancel your sprint.

**Comment by taytaytorro** [comment]
Thank you for leaving a report I am trying to work on fixing those bugs currently however i am having issues getting it working so please be patient if you would like you can roll back to the previous version
